### ISSUE TITLE
[EMAIL]: gib email 

### ISSUE THREAD

**Issue by SkyfallWasTaken** [zenith-hacks/infra#14]
### Contact Details

mahadkalam1@proton.me, hi@skyfall.dev, mahadkalam1234@gmail.com

### Your Name

Mahad Kalam

### Your New Zenith Hacks Email

mahad@zenithhacks.org

### Why do you need access?

I would like a Zenith Hacks email so I can send sponsorship requests 

### What is your role with Zenith Hacks

I am a core team member!

### Code of Conduct

- [X] I agree to follow Zenith Hack's Code of Conduct
- [X] I agree to follow Zenith Hack's Google Workspace Code of Conduct

**Comment by leowilkin** [comment]
sent to hi@skyfall.dev

**Comment by SkyfallWasTaken** [comment]
danke
