### ISSUE TITLE
[EMAIL]: Briyan's Email req!

### ISSUE THREAD

**Issue by briyandyju09** [zenith-hacks/infra#15]
### Contact Details

briyandyju@gmail.com && U04FS5WUXL3

### Your Name

Briyan George Dyju

### Your New Zenith Hacks Email

briyan@zenithhacks.org

### Why do you need access?

I would like a Zenith Hacks email so I can contact potential sponsors more professionally. 

### What is your role with Zenith Hacks

I am a core team member!

### Code of Conduct

- [X] I agree to follow Zenith Hack's Code of Conduct
- [X] I agree to follow Zenith Hack's Google Workspace Code of Conduct

**Comment by leowilkin** [comment]
done!
