### ISSUE TITLE
[HCB]: Briyan's HCB req!

### ISSUE THREAD

**Issue by briyandyju09** [zenith-hacks/infra#16]
### Contact Details

briyandyju@gmail.com && U04FS5WUXL3

### Why do you need access?

I'm working on sponsors for Zenith and would appreciate access to the HCB incase requested by any company or required by me to make an essential purchase that contributes to Zenith.

### Who are you?

I'm a Core Orga team member!

### Code of Conduct

- [X] I agree to follow Zenith Hacks' Code of Conduct

**Comment by leowilkin** [comment]
done!
