### ISSUE TITLE
[NTN]: 

### ISSUE THREAD

**Issue by ad-astraa** [zenith-hacks/infra#17]
### Contact Details

astronitika@gmail.com and @Astro 

### Why do you need access?

just incase

### Who are you?

I'm a Core Orga team member!

### Code of Conduct

- [X] I agree to follow Zenith Hacks' Code of Conduct

**Comment by astro** [comment]
I haven't gotten access yet

**Comment by leowilkin** [comment]
You've been given access:
https://www.notion.so/lkw/Zenith-2025-1d4c3bbb397f491b94f7873b82760cd5?pvs=4

Best Wishes,
Leo

Leo Wilkin
***@***.***
https://wilkin.xyz
