### ISSUE TITLE
[EMAIL]: sar :)

### ISSUE THREAD

**Issue by iamawatermelo** [zenith-hacks/infra#19]
### Contact Details

sharajarajsarahs / Sarah on Slack

### Your Name

Sarah C

### Your New Zenith Hacks Email

sarahc@zenithhacks.org

### Why do you need access?

I would like a Zenith Hacks email so I can access Loops to send out transactional and marketing emails

### What is your role with Zenith Hacks

I am a core team member!

### Code of Conduct

- [X] I agree to follow Zenith Hack's Code of Conduct
- [X] I agree to follow Zenith Hack's Google Workspace Code of Conduct

**Comment by leowilkin** [comment]
Can you send me your email for the backup @iamawatermelo pls!
