### ISSUE TITLE
[EMAIL]: jonathan@zenithhacks.org

### ISSUE THREAD

**Issue by Dongathan-Jong** [zenith-hacks/infra#2]
### Contact Details

@Ducc on slack

### Your Name

Jonathan Dong

### Your New Zenith Hacks Email

jonathan@zenithhacks.org

### Why do you need access?

I would like a Zenith Hacks email so I can help with sponsor outreach and organization

### What is your role with Zenith Hacks

I am a core team member!

### Code of Conduct

- [X] I agree to follow Zenith Hack's Code of Conduct
- [X] I agree to follow Zenith Hack's Google Workspace Code of Conduct

**Comment by leowilkin** [comment]
Can you send your email here please? Updating the issue form to be more specific
@Dongathan-Jong

**Comment by Dongathan-Jong** [comment]
Ah, didnt realise, jonathandong2020@gmail.com
