### ISSUE TITLE
[NTN]: Joining Zenith Org Team

### ISSUE THREAD

**Issue by Vihaan3** [zenith-hacks/infra#22]
### Contact Details

vihaansondhi07@gmail.com, @Vihaan Sondhi

### Why do you need access?

Rushil told me to fill out this web page to get added to the Zenith Hacks Notion. I'll be mostly helping out with sponsors and creating documentation for future hackathons to look at. 

### Who are you?

I'm a Core Orga team member!

### Code of Conduct

- [X] I agree to follow Zenith Hacks' Code of Conduct

**Comment by leowilkin** [comment]
done!
