### ISSUE TITLE
[NTN]: notiob

### ISSUE THREAD

**Issue by iamawatermelo** [zenith-hacks/infra#23]
### Contact Details

sharajarajsarahs on Slack

### Why do you need access?

Organising the team. Send the invite to my Zenith email

### Who are you?

I'm a Core Orga team member!

### Code of Conduct

- [X] I agree to follow Zenith Hacks' Code of Conduct

**Comment by leowilkin** [comment]
done!
Leo Wilkin

he/him
[image: mobilePhone] 07450970998
[image: emailAddress] ***@***.***
[image: website] wilkin.studio
[image: twitter] <https://www.twitter.com/lkwilk23>
