### ISSUE TITLE
[NTN]: Owais

### ISSUE THREAD

**Issue by Owais43** [zenith-hacks/infra#26]
### Contact Details

planningowais@gmail.com

### Why do you need access?

Adding sponsorship stuff and escape room planning

### Who are you?

I'm a Core Orga team member!

### Code of Conduct

- [x] I agree to follow Zenith Hacks' Code of Conduct

**Comment by leowilkin** [comment]
The escape room is currently unplanned - so please don't share this as an 'official' update.

**Comment by Owais43** [comment]
oop will do
