### ISSUE TITLE
[EMAIL]: Kerem Semiz kerem@zenithhacks.org

### ISSUE THREAD

**Issue by keremsemiz** [zenith-hacks/infra#36]
### Contact Details

@Kerem Semiz on Slack / kerem@hackclubberlin.com

### Your Name

Kerem Semiz

### Your New Zenith Hacks Email

kerem@zenithhacks.org

### Why do you need access?

to be taken seriously for sponsorship calls lol 😭

### What is your role with Zenith Hacks

I am a core team member!

### Code of Conduct

- [X] I agree to follow Zenith Hack's Code of Conduct
- [X] I agree to follow Zenith Hack's Google Workspace Code of Conduct

**Comment by leowilkin** [comment]
Sent!
