### ISSUE TITLE
[EMAIL]: hamza@zenith.org

### ISSUE THREAD

**Issue by hnasheralneam** [zenith-hacks/infra#6]
### Contact Details

hnasheralneam@gmail.com

### Your Name

Hamza Nasher-Alneam 

### Your New Zenith Hacks Email

hamza@zenithhacks.org

### Why do you need access?

I would like a Zenith Hacks email so I can manage branding assets and that sort of thing

### What is your role with Zenith Hacks

I am a core team member!

### Code of Conduct

- [X] I agree to follow Zenith Hack's Code of Conduct
- [X] I agree to follow Zenith Hack's Google Workspace Code of Conduct

**Comment by leowilkin** [comment]
done!
