### ISSUE TITLE
[EMAIL]: Zenithhacks Email request

### ISSUE THREAD

**Issue by snaeker58** [zenith-hacks/infra#7]
### Contact Details

@Sneako

### Your Name

Karl Wünsche

### Your New Zenith Hacks Email

karl@zenithhacks.org

### Why do you need access?

I would like a Zenith Hacks email so I can contact a few sponsors such as Boeing, Airbus and other sponsors who might help with travel costs. Also it could impress my Disney contacts in the hopes of getting more out of Disney!

### What is your role with Zenith Hacks

I am a participant!

### Code of Conduct

- [X] I agree to follow Zenith Hack's Code of Conduct
- [X] I agree to follow Zenith Hack's Google Workspace Code of Conduct

**Comment by leowilkin** [comment]
You need to add an email for verification from Google @snaeker58!

**Comment by snaeker58** [comment]
I‘m assuming you mean a Gmail? Or Google account linked email?

google@karl.my.id - linked with Google Account
snaeker58@gmail.com - not preferred but a Gmail address

**Comment by leowilkin** [comment]
it went to google@karl.my.id.

doesn't matter.
