### ISSUE TITLE
[EMAIL]: Leonard

### ISSUE THREAD

**Issue by L-S-2020** [zenith-hacks/infra#9]
### Contact Details

leonard@stegle.eu or @leost on slack

### Your Name

Leonard Stegle

### Your New Zenith Hacks Email

leonard@zenithhacks.org

### Why do you need access?

I would like a Zenith Hacks email so I can contact sponsors without looking like a scammer. P.S. Sorry for not following the workflow earlier.

### What is your role with Zenith Hacks

I am a core team member!

### Code of Conduct

- [X] I agree to follow Zenith Hack's Code of Conduct
- [X] I agree to follow Zenith Hack's Google Workspace Code of Conduct

**Comment by leowilkin** [comment]
all good!
